[weather-icons]
prefix = "wi"
font = "{__resources__}/icons/weathericons.ttf"

[weather-icons.chars]
day-sunny = "0xf00d"
day-cloudy = "0xf002"
day-cloudy-gusts = "0xf000"
day-cloudy-windy = "0xf001"
day-fog = "0xf003"
day-hail = "0xf004"
day-haze = "0xf0b6"
day-lightning = "0xf005"
day-rain = "0xf008"
day-rain-mix = "0xf006"
day-rain-wind = "0xf007"
day-showers = "0xf009"
day-sleet = "0xf0b2"
day-sleet-storm = "0xf068"
day-snow = "0xf00a"
day-snow-thunderstorm = "0xf06b"
day-snow-wind = "0xf065"
day-sprinkle = "0xf00b"
day-storm-showers = "0xf00e"
day-sunny-overcast = "0xf00c"
day-thunderstorm = "0xf010"
day-windy = "0xf085"
solar-eclipse = "0xf06e"
hot = "0xf072"
day-cloudy-high = "0xf07d"
day-light-wind = "0xf0c4"
night-clear = "0xf02e"
night-alt-cloudy = "0xf086"
night-alt-cloudy-gusts = "0xf022"
night-alt-cloudy-windy = "0xf023"
night-alt-hail = "0xf024"
night-alt-lightning = "0xf025"
night-alt-rain = "0xf028"
night-alt-rain-mix = "0xf026"
night-alt-rain-wind = "0xf027"
night-alt-showers = "0xf029"
night-alt-sleet = "0xf0b4"
night-alt-sleet-storm = "0xf06a"
night-alt-snow = "0xf02a"
night-alt-snow-thunderstorm = "0xf06d"
night-alt-snow-wind = "0xf067"
night-alt-sprinkle = "0xf02b"
night-alt-storm-showers = "0xf02c"
night-alt-thunderstorm = "0xf02d"
night-cloudy = "0xf031"
night-cloudy-gusts = "0xf02f"
night-cloudy-windy = "0xf030"
night-fog = "0xf04a"
night-hail = "0xf032"
night-lightning = "0xf033"
night-partly-cloudy = "0xf083"
night-rain = "0xf036"
night-rain-mix = "0xf034"
night-rain-wind = "0xf035"
night-showers = "0xf037"
night-sleet = "0xf0b3"
night-sleet-storm = "0xf069"
night-snow = "0xf038"
night-snow-thunderstorm = "0xf06c"
night-snow-wind = "0xf066"
night-sprinkle = "0xf039"
night-storm-showers = "0xf03a"
night-thunderstorm = "0xf03b"
lunar-eclipse = "0xf070"
stars = "0xf077"
storm-showers = "0xf01d"
thunderstorm = "0xf01e"
night-alt-cloudy-high = "0xf07e"
night-cloudy-high = "0xf080"
night-alt-partly-cloudy = "0xf081"
cloud = "0xf041"
cloudy = "0xf013"
cloudy-gusts = "0xf011"
cloudy-windy = "0xf012"
fog = "0xf014"
hail = "0xf015"
rain = "0xf019"
rain-mix = "0xf017"
rain-wind = "0xf018"
showers = "0xf01a"
sleet = "0xf0b5"
snow = "0xf01b"
sprinkle = "0xf01c"
snow-wind = "0xf064"
smog = "0xf074"
smoke = "0xf062"
lightning = "0xf016"
raindrops = "0xf04e"
raindrop = "0xf078"
dust = "0xf063"
snowflake-cold = "0xf076"
windy = "0xf021"
strong-wind = "0xf050"
sandstorm = "0xf082"
earthquake = "0xf0c6"
fire = "0xf0c7"
flood = "0xf07c"
meteor = "0xf071"
tsunami = "0xf0c5"
volcano = "0xf0c8"
hurricane = "0xf073"
tornado = "0xf056"
small-craft-advisory = "0xf0cc"
gale-warning = "0xf0cd"
storm-warning = "0xf0ce"
hurricane-warning = "0xf0cf"
wind-direction = "0xf0b1"
alien = "0xf075"
celsius = "0xf03c"
fahrenheit = "0xf045"
degrees = "0xf042"
thermometer = "0xf055"
thermometer-exterior = "0xf053"
thermometer-internal = "0xf054"
cloud-down = "0xf03d"
cloud-up = "0xf040"
cloud-refresh = "0xf03e"
horizon = "0xf047"
horizon-alt = "0xf046"
sunrise = "0xf051"
sunset = "0xf052"
moonrise = "0xf0c9"
moonset = "0xf0ca"
refresh = "0xf04c"
refresh-alt = "0xf04b"
umbrella = "0xf084"
barometer = "0xf079"
humidity = "0xf07a"
na = "0xf07b"
train = "0xf0cb"
moon-new = "0xf095"
moon-waxing-crescent-1 = "0xf096"
moon-waxing-crescent-2 = "0xf097"
moon-waxing-crescent-3 = "0xf098"
moon-waxing-crescent-4 = "0xf099"
moon-waxing-crescent-5 = "0xf09a"
moon-waxing-crescent-6 = "0xf09b"
moon-first-quarter = "0xf09c"
moon-waxing-gibbous-1 = "0xf09d"
moon-waxing-gibbous-2 = "0xf09e"
moon-waxing-gibbous-3 = "0xf09f"
moon-waxing-gibbous-4 = "0xf0a0"
moon-waxing-gibbous-5 = "0xf0a1"
moon-waxing-gibbous-6 = "0xf0a2"
moon-full = "0xf0a3"
moon-waning-gibbous-1 = "0xf0a4"
moon-waning-gibbous-2 = "0xf0a5"
moon-waning-gibbous-3 = "0xf0a6"
moon-waning-gibbous-4 = "0xf0a7"
moon-waning-gibbous-5 = "0xf0a8"
moon-waning-gibbous-6 = "0xf0a9"
moon-third-quarter = "0xf0aa"
moon-waning-crescent-1 = "0xf0ab"
moon-waning-crescent-2 = "0xf0ac"
moon-waning-crescent-3 = "0xf0ad"
moon-waning-crescent-4 = "0xf0ae"
moon-waning-crescent-5 = "0xf0af"
moon-waning-crescent-6 = "0xf0b0"
moon-alt-new = "0xf0eb"
moon-alt-waxing-crescent-1 = "0xf0d0"
moon-alt-waxing-crescent-2 = "0xf0d1"
moon-alt-waxing-crescent-3 = "0xf0d2"
moon-alt-waxing-crescent-4 = "0xf0d3"
moon-alt-waxing-crescent-5 = "0xf0d4"
moon-alt-waxing-crescent-6 = "0xf0d5"
moon-alt-first-quarter = "0xf0d6"
moon-alt-waxing-gibbous-1 = "0xf0d7"
moon-alt-waxing-gibbous-2 = "0xf0d8"
moon-alt-waxing-gibbous-3 = "0xf0d9"
moon-alt-waxing-gibbous-4 = "0xf0da"
moon-alt-waxing-gibbous-5 = "0xf0db"
moon-alt-waxing-gibbous-6 = "0xf0dc"
moon-alt-full = "0xf0dd"
moon-alt-waning-gibbous-1 = "0xf0de"
moon-alt-waning-gibbous-2 = "0xf0df"
moon-alt-waning-gibbous-3 = "0xf0e0"
moon-alt-waning-gibbous-4 = "0xf0e1"
moon-alt-waning-gibbous-5 = "0xf0e2"
moon-alt-waning-gibbous-6 = "0xf0e3"
moon-alt-third-quarter = "0xf0e4"
moon-alt-waning-crescent-1 = "0xf0e5"
moon-alt-waning-crescent-2 = "0xf0e6"
moon-alt-waning-crescent-3 = "0xf0e7"
moon-alt-waning-crescent-4 = "0xf0e8"
moon-alt-waning-crescent-5 = "0xf0e9"
moon-alt-waning-crescent-6 = "0xf0ea"
moon-0 = "0xf095"
moon-1 = "0xf096"
moon-2 = "0xf097"
moon-3 = "0xf098"
moon-4 = "0xf099"
moon-5 = "0xf09a"
moon-6 = "0xf09b"
moon-7 = "0xf09c"
moon-8 = "0xf09d"
moon-9 = "0xf09e"
moon-10 = "0xf09f"
moon-11 = "0xf0a0"
moon-12 = "0xf0a1"
moon-13 = "0xf0a2"
moon-14 = "0xf0a3"
moon-15 = "0xf0a4"
moon-16 = "0xf0a5"
moon-17 = "0xf0a6"
moon-18 = "0xf0a7"
moon-19 = "0xf0a8"
moon-20 = "0xf0a9"
moon-21 = "0xf0aa"
moon-22 = "0xf0ab"
moon-23 = "0xf0ac"
moon-24 = "0xf0ad"
moon-25 = "0xf0ae"
moon-26 = "0xf0af"
moon-27 = "0xf0b0"
time-1 = "0xf08a"
time-2 = "0xf08b"
time-3 = "0xf08c"
time-4 = "0xf08d"
time-5 = "0xf08e"
time-6 = "0xf08f"
time-7 = "0xf090"
time-8 = "0xf091"
time-9 = "0xf092"
time-10 = "0xf093"
time-11 = "0xf094"
time-12 = "0xf089"
direction-up = "0xf058"
direction-up-right = "0xf057"
direction-right = "0xf04d"
direction-down-right = "0xf088"
direction-down = "0xf044"
direction-down-left = "0xf043"
direction-left = "0xf048"
direction-up-left = "0xf087"
wind-beaufort-0 = "0xf0b7"
wind-beaufort-1 = "0xf0b8"
wind-beaufort-2 = "0xf0b9"
wind-beaufort-3 = "0xf0ba"
wind-beaufort-4 = "0xf0bb"
wind-beaufort-5 = "0xf0bc"
wind-beaufort-6 = "0xf0bd"
wind-beaufort-7 = "0xf0be"
wind-beaufort-8 = "0xf0bf"
wind-beaufort-9 = "0xf0c0"
wind-beaufort-10 = "0xf0c1"
wind-beaufort-11 = "0xf0c2"
wind-beaufort-12 = "0xf0c3"
yahoo-0 = "0xf056"
yahoo-1 = "0xf00e"
yahoo-2 = "0xf073"
yahoo-3 = "0xf01e"
yahoo-4 = "0xf01e"
yahoo-5 = "0xf017"
yahoo-6 = "0xf017"
yahoo-7 = "0xf017"
yahoo-8 = "0xf015"
yahoo-9 = "0xf01a"
yahoo-10 = "0xf015"
yahoo-11 = "0xf01a"
yahoo-12 = "0xf01a"
yahoo-13 = "0xf01b"
yahoo-14 = "0xf00a"
yahoo-15 = "0xf064"
yahoo-16 = "0xf01b"
yahoo-17 = "0xf015"
yahoo-18 = "0xf017"
yahoo-19 = "0xf063"
yahoo-20 = "0xf014"
yahoo-21 = "0xf021"
yahoo-22 = "0xf062"
yahoo-23 = "0xf050"
yahoo-24 = "0xf050"
yahoo-25 = "0xf076"
yahoo-26 = "0xf013"
yahoo-27 = "0xf031"
yahoo-28 = "0xf002"
yahoo-29 = "0xf031"
yahoo-30 = "0xf002"
yahoo-31 = "0xf02e"
yahoo-32 = "0xf00d"
yahoo-33 = "0xf083"
yahoo-34 = "0xf00c"
yahoo-35 = "0xf017"
yahoo-36 = "0xf072"
yahoo-37 = "0xf00e"
yahoo-38 = "0xf00e"
yahoo-39 = "0xf00e"
yahoo-40 = "0xf01a"
yahoo-41 = "0xf064"
yahoo-42 = "0xf01b"
yahoo-43 = "0xf064"
yahoo-44 = "0xf00c"
yahoo-45 = "0xf00e"
yahoo-46 = "0xf01b"
yahoo-47 = "0xf00e"
yahoo-3200 = "0xf077"
forecast-io-clear-day = "0xf00d"
forecast-io-clear-night = "0xf02e"
forecast-io-rain = "0xf019"
forecast-io-snow = "0xf01b"
forecast-io-sleet = "0xf0b5"
forecast-io-wind = "0xf050"
forecast-io-fog = "0xf014"
forecast-io-cloudy = "0xf013"
forecast-io-partly-cloudy-day = "0xf002"
forecast-io-partly-cloudy-night = "0xf031"
forecast-io-hail = "0xf015"
forecast-io-thunderstorm = "0xf01e"
forecast-io-tornado = "0xf056"
wmo4680-0 = "0xf055"
wmo4680-00 = "0xf055"
wmo4680-1 = "0xf013"
wmo4680-01 = "0xf013"
wmo4680-2 = "0xf055"
wmo4680-02 = "0xf055"
wmo4680-3 = "0xf013"
wmo4680-03 = "0xf013"
wmo4680-4 = "0xf014"
wmo4680-04 = "0xf014"
wmo4680-5 = "0xf014"
wmo4680-05 = "0xf014"
wmo4680-10 = "0xf014"
wmo4680-11 = "0xf014"
wmo4680-12 = "0xf016"
wmo4680-18 = "0xf050"
wmo4680-20 = "0xf014"
wmo4680-21 = "0xf017"
wmo4680-22 = "0xf017"
wmo4680-23 = "0xf019"
wmo4680-24 = "0xf01b"
wmo4680-25 = "0xf015"
wmo4680-26 = "0xf01e"
wmo4680-27 = "0xf063"
wmo4680-28 = "0xf063"
wmo4680-29 = "0xf063"
wmo4680-30 = "0xf014"
wmo4680-31 = "0xf014"
wmo4680-32 = "0xf014"
wmo4680-33 = "0xf014"
wmo4680-34 = "0xf014"
wmo4680-35 = "0xf014"
wmo4680-40 = "0xf017"
wmo4680-41 = "0xf01c"
wmo4680-42 = "0xf019"
wmo4680-43 = "0xf01c"
wmo4680-44 = "0xf019"
wmo4680-45 = "0xf015"
wmo4680-46 = "0xf015"
wmo4680-47 = "0xf01b"
wmo4680-48 = "0xf01b"
wmo4680-50 = "0xf01c"
wmo4680-51 = "0xf01c"
wmo4680-52 = "0xf019"
wmo4680-53 = "0xf019"
wmo4680-54 = "0xf076"
wmo4680-55 = "0xf076"
wmo4680-56 = "0xf076"
wmo4680-57 = "0xf01c"
wmo4680-58 = "0xf019"
wmo4680-60 = "0xf01c"
wmo4680-61 = "0xf01c"
wmo4680-62 = "0xf019"
wmo4680-63 = "0xf019"
wmo4680-64 = "0xf015"
wmo4680-65 = "0xf015"
wmo4680-66 = "0xf015"
wmo4680-67 = "0xf017"
wmo4680-68 = "0xf017"
wmo4680-70 = "0xf01b"
wmo4680-71 = "0xf01b"
wmo4680-72 = "0xf01b"
wmo4680-73 = "0xf01b"
wmo4680-74 = "0xf076"
wmo4680-75 = "0xf076"
wmo4680-76 = "0xf076"
wmo4680-77 = "0xf01b"
wmo4680-78 = "0xf076"
wmo4680-80 = "0xf019"
wmo4680-81 = "0xf01c"
wmo4680-82 = "0xf019"
wmo4680-83 = "0xf019"
wmo4680-84 = "0xf01d"
wmo4680-85 = "0xf017"
wmo4680-86 = "0xf017"
wmo4680-87 = "0xf017"
wmo4680-89 = "0xf015"
wmo4680-90 = "0xf016"
wmo4680-91 = "0xf01d"
wmo4680-92 = "0xf01e"
wmo4680-93 = "0xf01e"
wmo4680-94 = "0xf016"
wmo4680-95 = "0xf01e"
wmo4680-96 = "0xf01e"
wmo4680-99 = "0xf056"
owm-200 = "0xf01e"
owm-201 = "0xf01e"
owm-202 = "0xf01e"
owm-210 = "0xf016"
owm-211 = "0xf016"
owm-212 = "0xf016"
owm-221 = "0xf016"
owm-230 = "0xf01e"
owm-231 = "0xf01e"
owm-232 = "0xf01e"
owm-300 = "0xf01c"
owm-301 = "0xf01c"
owm-302 = "0xf019"
owm-310 = "0xf017"
owm-311 = "0xf019"
owm-312 = "0xf019"
owm-313 = "0xf01a"
owm-314 = "0xf019"
owm-321 = "0xf01c"
owm-500 = "0xf01c"
owm-501 = "0xf019"
owm-502 = "0xf019"
owm-503 = "0xf019"
owm-504 = "0xf019"
owm-511 = "0xf017"
owm-520 = "0xf01a"
owm-521 = "0xf01a"
owm-522 = "0xf01a"
owm-531 = "0xf01d"
owm-600 = "0xf01b"
owm-601 = "0xf01b"
owm-602 = "0xf0b5"
owm-611 = "0xf017"
owm-612 = "0xf017"
owm-615 = "0xf017"
owm-616 = "0xf017"
owm-620 = "0xf017"
owm-621 = "0xf01b"
owm-622 = "0xf01b"
owm-701 = "0xf01a"
owm-711 = "0xf062"
owm-721 = "0xf0b6"
owm-731 = "0xf063"
owm-741 = "0xf014"
owm-761 = "0xf063"
owm-762 = "0xf063"
owm-771 = "0xf011"
owm-781 = "0xf056"
owm-800 = "0xf00d"
owm-801 = "0xf011"
owm-802 = "0xf011"
owm-803 = "0xf012"
owm-804 = "0xf013"
owm-900 = "0xf056"
owm-901 = "0xf01d"
owm-902 = "0xf073"
owm-903 = "0xf076"
owm-904 = "0xf072"
owm-905 = "0xf021"
owm-906 = "0xf015"
owm-957 = "0xf050"
owm-day-200 = "0xf010"
owm-day-201 = "0xf010"
owm-day-202 = "0xf010"
owm-day-210 = "0xf005"
owm-day-211 = "0xf005"
owm-day-212 = "0xf005"
owm-day-221 = "0xf005"
owm-day-230 = "0xf010"
owm-day-231 = "0xf010"
owm-day-232 = "0xf010"
owm-day-300 = "0xf00b"
owm-day-301 = "0xf00b"
owm-day-302 = "0xf008"
owm-day-310 = "0xf008"
owm-day-311 = "0xf008"
owm-day-312 = "0xf008"
owm-day-313 = "0xf008"
owm-day-314 = "0xf008"
owm-day-321 = "0xf00b"
owm-day-500 = "0xf00b"
owm-day-501 = "0xf008"
owm-day-502 = "0xf008"
owm-day-503 = "0xf008"
owm-day-504 = "0xf008"
owm-day-511 = "0xf006"
owm-day-520 = "0xf009"
owm-day-521 = "0xf009"
owm-day-522 = "0xf009"
owm-day-531 = "0xf00e"
owm-day-600 = "0xf00a"
owm-day-601 = "0xf0b2"
owm-day-602 = "0xf00a"
owm-day-611 = "0xf006"
owm-day-612 = "0xf006"
owm-day-615 = "0xf006"
owm-day-616 = "0xf006"
owm-day-620 = "0xf006"
owm-day-621 = "0xf00a"
owm-day-622 = "0xf00a"
owm-day-701 = "0xf009"
owm-day-711 = "0xf062"
owm-day-721 = "0xf0b6"
owm-day-731 = "0xf063"
owm-day-741 = "0xf003"
owm-day-761 = "0xf063"
owm-day-762 = "0xf063"
owm-day-771 = "0xf000"
owm-day-781 = "0xf056"
owm-day-800 = "0xf00d"
owm-day-801 = "0xf000"
owm-day-802 = "0xf000"
owm-day-803 = "0xf000"
owm-day-804 = "0xf00c"
owm-day-900 = "0xf056"
owm-day-901 = "0xf00e"
owm-day-902 = "0xf073"
owm-day-903 = "0xf076"
owm-day-904 = "0xf072"
owm-day-905 = "0xf0c4"
owm-day-906 = "0xf004"
owm-day-957 = "0xf050"
owm-night-200 = "0xf02d"
owm-night-201 = "0xf02d"
owm-night-202 = "0xf02d"
owm-night-210 = "0xf025"
owm-night-211 = "0xf025"
owm-night-212 = "0xf025"
owm-night-221 = "0xf025"
owm-night-230 = "0xf02d"
owm-night-231 = "0xf02d"
owm-night-232 = "0xf02d"
owm-night-300 = "0xf02b"
owm-night-301 = "0xf02b"
owm-night-302 = "0xf028"
owm-night-310 = "0xf028"
owm-night-311 = "0xf028"
owm-night-312 = "0xf028"
owm-night-313 = "0xf028"
owm-night-314 = "0xf028"
owm-night-321 = "0xf02b"
owm-night-500 = "0xf02b"
owm-night-501 = "0xf028"
owm-night-502 = "0xf028"
owm-night-503 = "0xf028"
owm-night-504 = "0xf028"
owm-night-511 = "0xf026"
owm-night-520 = "0xf029"
owm-night-521 = "0xf029"
owm-night-522 = "0xf029"
owm-night-531 = "0xf02c"
owm-night-600 = "0xf02a"
owm-night-601 = "0xf0b4"
owm-night-602 = "0xf02a"
owm-night-611 = "0xf026"
owm-night-612 = "0xf026"
owm-night-615 = "0xf026"
owm-night-616 = "0xf026"
owm-night-620 = "0xf026"
owm-night-621 = "0xf02a"
owm-night-622 = "0xf02a"
owm-night-701 = "0xf029"
owm-night-711 = "0xf062"
owm-night-721 = "0xf0b6"
owm-night-731 = "0xf063"
owm-night-741 = "0xf04a"
owm-night-761 = "0xf063"
owm-night-762 = "0xf063"
owm-night-771 = "0xf022"
owm-night-781 = "0xf056"
owm-night-800 = "0xf02e"
owm-night-801 = "0xf022"
owm-night-802 = "0xf022"
owm-night-803 = "0xf022"
owm-night-804 = "0xf086"
owm-night-900 = "0xf056"
owm-night-901 = "0xf03a"
owm-night-902 = "0xf073"
owm-night-903 = "0xf076"
owm-night-904 = "0xf072"
owm-night-905 = "0xf021"
owm-night-906 = "0xf024"
owm-night-957 = "0xf050"
wu-chanceflurries = "0xf064"
wu-chancerain = "0xf019"
wu-chancesleat = "0xf0b5"
wu-chancesnow = "0xf01b"
wu-chancetstorms = "0xf01e"
wu-clear = "0xf00d"
wu-cloudy = "0xf002"
wu-flurries = "0xf064"
wu-hazy = "0xf0b6"
wu-mostlycloudy = "0xf002"
wu-mostlysunny = "0xf00d"
wu-partlycloudy = "0xf002"
wu-partlysunny = "0xf00d"
wu-rain = "0xf01a"
wu-sleat = "0xf0b5"
wu-snow = "0xf01b"
wu-sunny = "0xf00d"
wu-tstorms = "0xf01e"
wu-unknown = "0xf00d"